force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <label>Adoption Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/adoption_date__c.field-meta.xml
<CustomField>
    <fullName>adoption_date__c</fullName>
    <label>adoption date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Adoptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipName>Adoptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>In approval</fullName>
            </value>
            <value>
                <fullName>Pending pet search</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Adoption__c.field-meta.xml
<CustomField>
    <fullName>Adoption__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adoption</label>
    <referenceTo>Adoption__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>FLOOR((TODAY() - Birthdate) / 365.2425)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Adoption__c.field-meta.xml
<CustomField>
    <fullName>Adoption__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adoption</label>
    <referenceTo>Adoption__c</referenceTo>
    <relationshipLabel>Pets</relationshipLabel>
    <relationshipName>Pets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Species__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mixed breed</fullName>
            </value>
            <value>
                <fullName>poodle</fullName>
            </value>
            <value>
                <fullName>siamese</fullName>
            </value>
            <value>
                <fullName>persian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdoptionController.cls
public with sharing class AdoptionController {
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getAdoptionDetails(Id adoptionId) {
        Adoption__c adoption = [
            SELECT Contact__r.Name, Contact__r.Age__c, Pet__r.Name, Pet__r.Race__c, adoption_date__c, State__c 
            FROM Adoption__c 
            WHERE Id = :adoptionId
        ];
        return new Map<String, Object>{
            'contactName' => adoption.Contact__r.Name,
            'contactAge' => adoption.Contact__r.Age__c,
            'petName' => adoption.Pet__r.Name,
            'petBreed' => adoption.Pet__r.Race__c,
            'adoptionDate' => adoption.adoption_date__c,
            'adopted' => adoption.State__c == 'Completed'
        };
    }
}